// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgvIm1ghdKG_qz36xUVwYFZPZqTraGAc',
    appId: '1:473322915725:web:2798c6e7a37d86d2549fc4',
    messagingSenderId: '473322915725',
    projectId: 'chemba-e1aa9',
    authDomain: 'chemba-e1aa9.firebaseapp.com',
    storageBucket: 'chemba-e1aa9.appspot.com',
    measurementId: 'G-BYE1CLQ94P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fwnvt70ovgvcTR--xrtttX3Y6loYY5c',
    appId: '1:473322915725:android:66fc4aa910abf6e9549fc4',
    messagingSenderId: '473322915725',
    projectId: 'chemba-e1aa9',
    storageBucket: 'chemba-e1aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj-AO6ZmbTcgRolaQyAKJr5IVxelkXxs',
    appId: '1:473322915725:ios:2b9c136ff4c3ee00549fc4',
    messagingSenderId: '473322915725',
    projectId: 'chemba-e1aa9',
    storageBucket: 'chemba-e1aa9.appspot.com',
    iosClientId: '473322915725-msh4se0csg707gbj6400sq57o1smuq29.apps.googleusercontent.com',
    iosBundleId: 'com.gabina.chemba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj-AO6ZmbTcgRolaQyAKJr5IVxelkXxs',
    appId: '1:473322915725:ios:2b9c136ff4c3ee00549fc4',
    messagingSenderId: '473322915725',
    projectId: 'chemba-e1aa9',
    storageBucket: 'chemba-e1aa9.appspot.com',
    iosClientId: '473322915725-msh4se0csg707gbj6400sq57o1smuq29.apps.googleusercontent.com',
    iosBundleId: 'com.gabina.chemba',
  );
}
